targets:
  $default:
    builders:
      freezed:
        enabled: true
        options:
          # Opciones de freezed
          union_key: 'type'
          union_value_case: 'pascal'
      
      json_serializable:
        enabled: true
        options:
          # Opciones de json_serializable
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
      
      riverpod_generator:
        enabled: true
